name 'jenkins_slave_ok'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures jenkins_slave_ok'
long_description 'Installs/Configures jenkins_slave_ok'
version '0.1.0'
